# AML Platform Support
snd-soc-aml-pcm-bt-objs := aml_pcm_bt.o
snd-soc-aml-pcm-objs := aml_pcm.o
snd-soc-aml-dai-objs := aml_dai.o
snd-soc-aml-hw-objs  := aml_audio_hw.o
snd-soc-aml-pcm-bt-hw-objs := aml_pcm_bt_hw.o
snd-soc-aml-platform-objs := aml_platform.o


obj-$(CONFIG_SND_AML_M3) += snd-soc-aml-pcm.o
obj-$(CONFIG_SND_AML_M3) += snd-soc-aml-dai.o
obj-$(CONFIG_SND_AML_M3) += snd-soc-aml-hw.o
obj-$(CONFIG_SND_AML_M3) += aml_notify.o
obj-$(CONFIG_SND_AML_M3) += snd-soc-aml-platform.o
obj-$(CONFIG_SND_AML_M3_PCM) += snd-soc-aml-pcm-bt.o
obj-$(CONFIG_SND_AML_M3_PCM) += snd-soc-aml-pcm-bt-hw.o


# AML M3 Machine support
snd-soc-aml-codec-objs := aml_m3_codec.o
obj-$(CONFIG_SND_AML_M3) += snd-soc-aml-codec.o

snd-soc-aml-m3-objs := aml_m3.o
obj-$(CONFIG_SND_AML_M3) += snd-soc-aml-m3.o


#AML M3 with CS4334 support

snd-soc-aml-m3-cs4334-objs := aml_m3_cs4334.o
obj-$(CONFIG_SND_AML_M3_CS4334) += snd-soc-aml-m3-cs4334.o


